window.esdocSearchIndex = [
  [
    "shepherd.js/src/js/evented.js~evented",
    "class/src/js/evented.js~Evented.html",
    "<span>Evented</span> <span class=\"search-result-import-path\">shepherd.js/src/js/evented.js</span>",
    "class"
  ],
  [
    "shepherd.js/src/js/modal.js~modal",
    "class/src/js/modal.js~Modal.html",
    "<span>Modal</span> <span class=\"search-result-import-path\">shepherd.js/src/js/modal.js</span>",
    "class"
  ],
  [
    "shepherd.js/src/js/tour.js~shepherd",
    "variable/index.html#static-variable-Shepherd",
    "<span>Shepherd</span> <span class=\"search-result-import-path\">shepherd.js/src/js/tour.js</span>",
    "variable"
  ],
  [
    "shepherd.js/src/js/step.js~step",
    "class/src/js/step.js~Step.html",
    "<span>Step</span> <span class=\"search-result-import-path\">shepherd.js/src/js/step.js</span>",
    "class"
  ],
  [
    "shepherd.js/src/js/tour.js~tour",
    "class/src/js/tour.js~Tour.html",
    "<span>Tour</span> <span class=\"search-result-import-path\">shepherd.js/src/js/tour.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/cypress/integration/element-targeting.spec.js.html#lineNumber4",
    "Attaching tooltips to target elements in the DOM on each step",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/element-targeting.spec.js.html#lineNumber20",
    "Attaching tooltips to target elements in the DOM on each step Adding/Removing class names to the target of the current step",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/element-targeting.spec.js.html#lineNumber31",
    "Attaching tooltips to target elements in the DOM on each step Adding/Removing class names to the target of the current step Adds the \"shepherd-target\" and \"shepherd-enabled\" classes upon showing a step",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/element-targeting.spec.js.html#lineNumber39",
    "Attaching tooltips to target elements in the DOM on each step Adding/Removing class names to the target of the current step Removes the \"shepherd-target\" and \"shepherd-enabled\" upon hiding a step",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/cleanup.spec.js.html#lineNumber3",
    "Cleanup Utils",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/cleanup.spec.js.html#lineNumber41",
    "Cleanup Utils cleanupStepEventListeners",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/cleanup.spec.js.html#lineNumber42",
    "Cleanup Utils cleanupStepEventListeners removes listeners",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/cleanup.spec.js.html#lineNumber32",
    "Cleanup Utils cleanupSteps",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/cleanup.spec.js.html#lineNumber33",
    "Cleanup Utils cleanupSteps cleans up steps and sets pointer-events to auto",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber6",
    "DOM Utils",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber7",
    "DOM Utils elementIsHidden",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber8",
    "DOM Utils elementIsHidden returns true when hidden",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber17",
    "DOM Utils getElementForStep",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber18",
    "DOM Utils getElementForStep attachTo object - element is HTMLElement",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber32",
    "DOM Utils getElementForStep attachTo object - element is selector",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/dom.spec.js.html#lineNumber49",
    "DOM Utils getElementForStep attachTo string",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber3",
    "Evented",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber25",
    "Evented off()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber39",
    "Evented off() does not remove uncreated events",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber26",
    "Evented off() removes a generic event binding when no handler passed",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber31",
    "Evented off() removes a specific event binding when handler is passed",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber12",
    "Evented on()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber13",
    "Evented on() adds a new event binding",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber44",
    "Evented once()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber45",
    "Evented once() adds a new event binding that only triggers once",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber18",
    "Evented trigger()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/evented.spec.js.html#lineNumber19",
    "Evented trigger() triggers a created event",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber6",
    "Modal",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/modal.spec.js.html#lineNumber8",
    "Modal Utils",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/modal.spec.js.html#lineNumber9",
    "Modal Utils closeModalOpening",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/modal.spec.js.html#lineNumber10",
    "Modal Utils closeModalOpening sets the correct attributes when closed",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/modal.spec.js.html#lineNumber26",
    "Modal Utils positionModalOpening",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/modal.spec.js.html#lineNumber27",
    "Modal Utils positionModalOpening sets the correct attributes when positioning modal opening",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/modal.spec.js.html#lineNumber47",
    "Modal Utils positionModalOpening sets the correct attributes with padding",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber25",
    "Modal createModalOverlay()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber26",
    "Modal createModalOverlay() appends shepherdModalOverlayContainer to DOM when it does not exist",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber33",
    "Modal createModalOverlay() reuses shepherdModalOverlayContainer rather than making a new one",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber9",
    "Modal mode",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber45",
    "Modal mode Modal disabled",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber52",
    "Modal mode Modal disabled Hiding the modal during tours when modal mode is not enabled",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber30",
    "Modal mode Modal enabled",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber37",
    "Modal mode Modal enabled Displaying the modal during tours when modal mode is enabled",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber60",
    "Modal mode hide",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber65",
    "Modal mode hide removes shepherd-modal-is-visible class from the BODY",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber76",
    "Modal mode highlight",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/modal.spec.js.html#lineNumber96",
    "Modal mode highlight applying highlight classes to the target element",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber44",
    "Modal setupForStep()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber52",
    "Modal setupForStep() useModalOverlay: false, hides modal",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber63",
    "Modal setupForStep() useModalOverlay: true, shows modal",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber7",
    "Modal show/hide",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber17",
    "Modal show/hide hide removes classes",
    "test"
  ],
  [
    "",
    "test-file/test/unit/modal.spec.js.html#lineNumber10",
    "Modal show/hide show adds classes",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber13",
    "Tour | Step",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber14",
    "Tour | Step Shepherd.Step()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber104",
    "Tour | Step Shepherd.Step() .hide()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber105",
    "Tour | Step Shepherd.Step() .hide() detaches from the step target",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber118",
    "Tour | Step Shepherd.Step() .show()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber119",
    "Tour | Step Shepherd.Step() .show() beforeShowPromise called before `show`",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber127",
    "Tour | Step Shepherd.Step() .show() shows step evoking method, regardless of order",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber95",
    "Tour | Step Shepherd.Step() has all the correct properties",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber524",
    "Tour | Step _addButtons",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber545",
    "Tour | Step _addButtons renders buttons for each item passed to `options.buttons`",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber525",
    "Tour | Step _addButtons renders no buttons if an empty array is passed to `options.buttons`",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber536",
    "Tour | Step _addButtons renders no buttons if nothing is passed to `options.buttons`",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber585",
    "Tour | Step _addCancelLink",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber586",
    "Tour | Step _addCancelLink Cancel link",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber478",
    "Tour | Step _addContent()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber479",
    "Tour | Step _addContent() adds plain text to the content",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber500",
    "Tour | Step _addContent() applies HTML element directly to content",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber512",
    "Tour | Step _addContent() applies the text from a function",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber489",
    "Tour | Step _addContent() maps mutiple strings to paragraphs",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber568",
    "Tour | Step _addKeyDownHandler",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber569",
    "Tour | Step _addKeyDownHandler ESC cancels the tour",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber601",
    "Tour | Step _createTooltipContent",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber602",
    "Tour | Step _createTooltipContent ARIA attributes set",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber135",
    "Tour | Step bindAdvance()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber222",
    "Tour | Step bindAdvance() calls `removeEventListener` when destroyed",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber190",
    "Tour | Step bindAdvance() captures events attached to no element",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber203",
    "Tour | Step bindAdvance() should support bubbling events for nodes that do not exist yet",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber176",
    "Tour | Step bindAdvance() triggers the `advanceOn` option via object",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber162",
    "Tour | Step bindAdvance() triggers the `advanceOn` option via string",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber240",
    "Tour | Step bindButtonEvents()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber243",
    "Tour | Step bindButtonEvents() adds button events",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber262",
    "Tour | Step bindButtonEvents() removes events once destroyed",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber270",
    "Tour | Step bindCancelLink()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber271",
    "Tour | Step bindCancelLink() adds an event handler for the cancel button",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber289",
    "Tour | Step bindMethods()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber290",
    "Tour | Step bindMethods() binds the expected methods",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber309",
    "Tour | Step cancel()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber310",
    "Tour | Step cancel() triggers the cancel event and tour method",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber326",
    "Tour | Step complete()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber327",
    "Tour | Step complete() triggers the complete event and tour method",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber343",
    "Tour | Step destroy()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber344",
    "Tour | Step destroy() triggers the destroy event",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber469",
    "Tour | Step getTour()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber470",
    "Tour | Step getTour() returns the tour value",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber354",
    "Tour | Step hide()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber376",
    "Tour | Step hide() calls tour.modal.hide",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber380",
    "Tour | Step hide() removes the data-shepherd-step attribute",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber369",
    "Tour | Step hide() triggers the before-hide event",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber385",
    "Tour | Step parseAttachTo()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber386",
    "Tour | Step parseAttachTo() fails if element does not exist",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber429",
    "Tour | Step scrollTo()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber444",
    "Tour | Step scrollTo() calls the custom handler",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber430",
    "Tour | Step scrollTo() calls the scroll native method",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber455",
    "Tour | Step setOptions()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber456",
    "Tour | Step setOptions() calls event handlers passed in as properties to the `when` option",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber396",
    "Tour | Step setupElements()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber416",
    "Tour | Step setupElements() calls bindAdvance() if advanceOn passed",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber397",
    "Tour | Step setupElements() calls destroy on the step if the content element is already set",
    "test"
  ],
  [
    "",
    "test-file/test/unit/step.spec.js.html#lineNumber406",
    "Tour | Step setupElements() calls destroy on the tooltip if it already exists",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber15",
    "Tour | Top-Level Class",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber31",
    "Tour | Top-Level Class constructor",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber32",
    "Tour | Top-Level Class constructor creates a new tour instance",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber71",
    "Tour | Top-Level Class constructor generates a unique `id` property, optionally based upon the `tourName` option",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber38",
    "Tour | Top-Level Class constructor returns the default options on the instance",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber57",
    "Tour | Top-Level Class constructor sets defaults for tippy",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber47",
    "Tour | Top-Level Class constructor sets the correct bindings",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber85",
    "Tour | Top-Level Class methods",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber118",
    "Tour | Top-Level Class methods .addStep()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber133",
    "Tour | Top-Level Class methods .addStep() adds steps that are already Step instances",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber124",
    "Tour | Top-Level Class methods .addStep() adds steps with only one arg",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber119",
    "Tour | Top-Level Class methods .addStep() adds tour steps",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber228",
    "Tour | Top-Level Class methods .cancel()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber229",
    "Tour | Top-Level Class methods .cancel() shows confirm dialog when confirmCancel is true",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber261",
    "Tour | Top-Level Class methods .cancel() tears down tour on cancel",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber273",
    "Tour | Top-Level Class methods .cancel() triggers cancel event when cancel function is called",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber285",
    "Tour | Top-Level Class methods .complete()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber298",
    "Tour | Top-Level Class methods .complete() calls `done()`",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber286",
    "Tour | Top-Level Class methods .complete() triggers complete event when complete function is called",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber310",
    "Tour | Top-Level Class methods .done()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber343",
    "Tour | Top-Level Class methods .done() fires the `inactive` event",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber321",
    "Tour | Top-Level Class methods .done() removes any of its `Step` tooltip elements from the DOM",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber311",
    "Tour | Top-Level Class methods .done() tears down the active tour",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber144",
    "Tour | Top-Level Class methods .getById()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber145",
    "Tour | Top-Level Class methods .getById() returns the step by ID with the right title",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber167",
    "Tour | Top-Level Class methods .getCurrentStep()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber168",
    "Tour | Top-Level Class methods .getCurrentStep() returns the currently shown step",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber174",
    "Tour | Top-Level Class methods .hide()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber175",
    "Tour | Top-Level Class methods .hide() hides the current step",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber205",
    "Tour | Top-Level Class methods .next()/.back()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber206",
    "Tour | Top-Level Class methods .next()/.back() goes to the next/previous steps",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber214",
    "Tour | Top-Level Class methods .next()/.back() next completes tour when on last step",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber360",
    "Tour | Top-Level Class methods .removeStep()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber368",
    "Tour | Top-Level Class methods .removeStep() hides the step before removing",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber361",
    "Tour | Top-Level Class methods .removeStep() removes the step when passed the id",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber382",
    "Tour | Top-Level Class methods .show()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber422",
    "Tour | Top-Level Class methods .show() ",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber391",
    "Tour | Top-Level Class methods .show() show short-circuits if next is not found",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber401",
    "Tour | Top-Level Class methods .show() showOn determines which steps to skip",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber151",
    "Tour | Top-Level Class methods .start()",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber158",
    "Tour | Top-Level Class methods .start() adds the current tour's \"id\" property to the body as a data attribute",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber152",
    "Tour | Top-Level Class methods .start() starts a tour that is the current active",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber192",
    "Tour | Top-Level Class methods isActive",
    "test"
  ],
  [
    "",
    "test-file/test/unit/tour.spec.js.html#lineNumber193",
    "Tour | Top-Level Class methods isActive computes whether or not `Shepherd.activeTour` equals the instance",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber6",
    "Utils",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber7",
    "Utils _parseAttachToOpts",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber18",
    "Utils _parseAttachToOpts attachTo as a string",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber8",
    "Utils _parseAttachToOpts attachTo as an object",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber28",
    "Utils parseShorthand",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber29",
    "Utils parseShorthand null or undefined",
    "test"
  ],
  [
    "",
    "test-file/test/unit/utils/general.spec.js.html#lineNumber34",
    "Utils parseShorthand string of values",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber4",
    "a11y",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber20",
    "a11y focus",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber31",
    "a11y focus shepherd-element should have focus on tour start",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber38",
    "a11y keydown events",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber59",
    "a11y keydown events ESC cancels the tour",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber67",
    "a11y keydown events Tab is focus trapped inside the modal",
    "test"
  ],
  [
    "",
    "test-file/test/cypress/integration/a11y.spec.js.html#lineNumber49",
    "a11y keydown events arrows trigger back/next",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/eager/installhelper.js",
    "file/src/eager/installHelper.js.html",
    "src/eager/installHelper.js",
    "file"
  ],
  [
    "src/js/evented.js",
    "file/src/js/evented.js.html",
    "src/js/evented.js",
    "file"
  ],
  [
    "src/js/evented.js~evented#bindings",
    "class/src/js/evented.js~Evented.html#instance-member-bindings",
    "src/js/evented.js~Evented#bindings",
    "member"
  ],
  [
    "src/js/evented.js~evented#off",
    "class/src/js/evented.js~Evented.html#instance-method-off",
    "src/js/evented.js~Evented#off",
    "method"
  ],
  [
    "src/js/evented.js~evented#on",
    "class/src/js/evented.js~Evented.html#instance-method-on",
    "src/js/evented.js~Evented#on",
    "method"
  ],
  [
    "src/js/evented.js~evented#once",
    "class/src/js/evented.js~Evented.html#instance-method-once",
    "src/js/evented.js~Evented#once",
    "method"
  ],
  [
    "src/js/evented.js~evented#trigger",
    "class/src/js/evented.js~Evented.html#instance-method-trigger",
    "src/js/evented.js~Evented#trigger",
    "method"
  ],
  [
    "src/js/modal.js",
    "file/src/js/modal.js.html",
    "src/js/modal.js",
    "file"
  ],
  [
    "src/js/modal.js~modal#_modaloverlayelem",
    "class/src/js/modal.js~Modal.html#instance-member-_modalOverlayElem",
    "src/js/modal.js~Modal#_modalOverlayElem",
    "member"
  ],
  [
    "src/js/modal.js~modal#_modaloverlayopening",
    "class/src/js/modal.js~Modal.html#instance-member-_modalOverlayOpening",
    "src/js/modal.js~Modal#_modalOverlayOpening",
    "member"
  ],
  [
    "src/js/modal.js~modal#_onscreenchange",
    "class/src/js/modal.js~Modal.html#instance-member-_onScreenChange",
    "src/js/modal.js~Modal#_onScreenChange",
    "member"
  ],
  [
    "src/js/modal.js~modal#_styleforstep",
    "class/src/js/modal.js~Modal.html#instance-method-_styleForStep",
    "src/js/modal.js~Modal#_styleForStep",
    "method"
  ],
  [
    "src/js/modal.js~modal#cleanup",
    "class/src/js/modal.js~Modal.html#instance-method-cleanup",
    "src/js/modal.js~Modal#cleanup",
    "method"
  ],
  [
    "src/js/modal.js~modal#constructor",
    "class/src/js/modal.js~Modal.html#instance-constructor-constructor",
    "src/js/modal.js~Modal#constructor",
    "method"
  ],
  [
    "src/js/modal.js~modal#createmodaloverlay",
    "class/src/js/modal.js~Modal.html#instance-method-createModalOverlay",
    "src/js/modal.js~Modal#createModalOverlay",
    "method"
  ],
  [
    "src/js/modal.js~modal#hide",
    "class/src/js/modal.js~Modal.html#instance-method-hide",
    "src/js/modal.js~Modal#hide",
    "method"
  ],
  [
    "src/js/modal.js~modal#options",
    "class/src/js/modal.js~Modal.html#instance-member-options",
    "src/js/modal.js~Modal#options",
    "member"
  ],
  [
    "src/js/modal.js~modal#setupforstep",
    "class/src/js/modal.js~Modal.html#instance-method-setupForStep",
    "src/js/modal.js~Modal#setupForStep",
    "method"
  ],
  [
    "src/js/modal.js~modal#show",
    "class/src/js/modal.js~Modal.html#instance-method-show",
    "src/js/modal.js~Modal#show",
    "method"
  ],
  [
    "src/js/shepherd.js",
    "file/src/js/shepherd.js.html",
    "src/js/shepherd.js",
    "file"
  ],
  [
    "src/js/step.js",
    "file/src/js/step.js.html",
    "src/js/step.js",
    "file"
  ],
  [
    "src/js/step.js~step#_addbuttons",
    "class/src/js/step.js~Step.html#instance-method-_addButtons",
    "src/js/step.js~Step#_addButtons",
    "method"
  ],
  [
    "src/js/step.js~step#_addcancellink",
    "class/src/js/step.js~Step.html#instance-method-_addCancelLink",
    "src/js/step.js~Step#_addCancelLink",
    "method"
  ],
  [
    "src/js/step.js~step#_addcontent",
    "class/src/js/step.js~Step.html#instance-method-_addContent",
    "src/js/step.js~Step#_addContent",
    "method"
  ],
  [
    "src/js/step.js~step#_addkeydownhandler",
    "class/src/js/step.js~Step.html#instance-method-_addKeyDownHandler",
    "src/js/step.js~Step#_addKeyDownHandler",
    "method"
  ],
  [
    "src/js/step.js~step#_createtooltipcontent",
    "class/src/js/step.js~Step.html#instance-method-_createTooltipContent",
    "src/js/step.js~Step#_createTooltipContent",
    "method"
  ],
  [
    "src/js/step.js~step#_show",
    "class/src/js/step.js~Step.html#instance-method-_show",
    "src/js/step.js~Step#_show",
    "method"
  ],
  [
    "src/js/step.js~step#_updatesteptargetonhide",
    "class/src/js/step.js~Step.html#instance-method-_updateStepTargetOnHide",
    "src/js/step.js~Step#_updateStepTargetOnHide",
    "method"
  ],
  [
    "src/js/step.js~step#bindadvance",
    "class/src/js/step.js~Step.html#instance-member-bindAdvance",
    "src/js/step.js~Step#bindAdvance",
    "member"
  ],
  [
    "src/js/step.js~step#bindbuttonevents",
    "class/src/js/step.js~Step.html#instance-member-bindButtonEvents",
    "src/js/step.js~Step#bindButtonEvents",
    "member"
  ],
  [
    "src/js/step.js~step#bindcancellink",
    "class/src/js/step.js~Step.html#instance-member-bindCancelLink",
    "src/js/step.js~Step#bindCancelLink",
    "member"
  ],
  [
    "src/js/step.js~step#cancel",
    "class/src/js/step.js~Step.html#instance-method-cancel",
    "src/js/step.js~Step#cancel",
    "method"
  ],
  [
    "src/js/step.js~step#complete",
    "class/src/js/step.js~Step.html#instance-method-complete",
    "src/js/step.js~Step#complete",
    "method"
  ],
  [
    "src/js/step.js~step#constructor",
    "class/src/js/step.js~Step.html#instance-constructor-constructor",
    "src/js/step.js~Step#constructor",
    "method"
  ],
  [
    "src/js/step.js~step#destroy",
    "class/src/js/step.js~Step.html#instance-method-destroy",
    "src/js/step.js~Step#destroy",
    "method"
  ],
  [
    "src/js/step.js~step#el",
    "class/src/js/step.js~Step.html#instance-member-el",
    "src/js/step.js~Step#el",
    "member"
  ],
  [
    "src/js/step.js~step#gettour",
    "class/src/js/step.js~Step.html#instance-method-getTour",
    "src/js/step.js~Step#getTour",
    "method"
  ],
  [
    "src/js/step.js~step#hide",
    "class/src/js/step.js~Step.html#instance-method-hide",
    "src/js/step.js~Step#hide",
    "method"
  ],
  [
    "src/js/step.js~step#id",
    "class/src/js/step.js~Step.html#instance-member-id",
    "src/js/step.js~Step#id",
    "member"
  ],
  [
    "src/js/step.js~step#isopen",
    "class/src/js/step.js~Step.html#instance-method-isOpen",
    "src/js/step.js~Step#isOpen",
    "method"
  ],
  [
    "src/js/step.js~step#options",
    "class/src/js/step.js~Step.html#instance-member-options",
    "src/js/step.js~Step#options",
    "member"
  ],
  [
    "src/js/step.js~step#parseattachto",
    "class/src/js/step.js~Step.html#instance-member-parseAttachTo",
    "src/js/step.js~Step#parseAttachTo",
    "member"
  ],
  [
    "src/js/step.js~step#scrollto",
    "class/src/js/step.js~Step.html#instance-method-scrollTo",
    "src/js/step.js~Step#scrollTo",
    "method"
  ],
  [
    "src/js/step.js~step#setoptions",
    "class/src/js/step.js~Step.html#instance-method-setOptions",
    "src/js/step.js~Step#setOptions",
    "method"
  ],
  [
    "src/js/step.js~step#setupelements",
    "class/src/js/step.js~Step.html#instance-method-setupElements",
    "src/js/step.js~Step#setupElements",
    "method"
  ],
  [
    "src/js/step.js~step#setuptooltip",
    "class/src/js/step.js~Step.html#instance-member-setupTooltip",
    "src/js/step.js~Step#setupTooltip",
    "member"
  ],
  [
    "src/js/step.js~step#show",
    "class/src/js/step.js~Step.html#instance-method-show",
    "src/js/step.js~Step#show",
    "method"
  ],
  [
    "src/js/step.js~step#tooltip",
    "class/src/js/step.js~Step.html#instance-member-tooltip",
    "src/js/step.js~Step#tooltip",
    "member"
  ],
  [
    "src/js/step.js~step#tour",
    "class/src/js/step.js~Step.html#instance-member-tour",
    "src/js/step.js~Step#tour",
    "member"
  ],
  [
    "src/js/tour.js",
    "file/src/js/tour.js.html",
    "src/js/tour.js",
    "file"
  ],
  [
    "src/js/tour.js~tour#_addbodyattrs",
    "class/src/js/tour.js~Tour.html#instance-method-_addBodyAttrs",
    "src/js/tour.js~Tour#_addBodyAttrs",
    "method"
  ],
  [
    "src/js/tour.js~tour#_removebodyattrs",
    "class/src/js/tour.js~Tour.html#instance-method-_removeBodyAttrs",
    "src/js/tour.js~Tour#_removeBodyAttrs",
    "method"
  ],
  [
    "src/js/tour.js~tour#_settooltipdefaults",
    "class/src/js/tour.js~Tour.html#instance-method-_setTooltipDefaults",
    "src/js/tour.js~Tour#_setTooltipDefaults",
    "method"
  ],
  [
    "src/js/tour.js~tour#_settourid",
    "class/src/js/tour.js~Tour.html#instance-method-_setTourID",
    "src/js/tour.js~Tour#_setTourID",
    "method"
  ],
  [
    "src/js/tour.js~tour#_setupactivetour",
    "class/src/js/tour.js~Tour.html#instance-method-_setupActiveTour",
    "src/js/tour.js~Tour#_setupActiveTour",
    "method"
  ],
  [
    "src/js/tour.js~tour#_skipstep",
    "class/src/js/tour.js~Tour.html#instance-method-_skipStep",
    "src/js/tour.js~Tour#_skipStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#_styletargetelementforstep",
    "class/src/js/tour.js~Tour.html#instance-method-_styleTargetElementForStep",
    "src/js/tour.js~Tour#_styleTargetElementForStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#_updatestatebeforeshow",
    "class/src/js/tour.js~Tour.html#instance-method-_updateStateBeforeShow",
    "src/js/tour.js~Tour#_updateStateBeforeShow",
    "method"
  ],
  [
    "src/js/tour.js~tour#addstep",
    "class/src/js/tour.js~Tour.html#instance-method-addStep",
    "src/js/tour.js~Tour#addStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#back",
    "class/src/js/tour.js~Tour.html#instance-method-back",
    "src/js/tour.js~Tour#back",
    "method"
  ],
  [
    "src/js/tour.js~tour#beforeshowstep",
    "class/src/js/tour.js~Tour.html#instance-method-beforeShowStep",
    "src/js/tour.js~Tour#beforeShowStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#cancel",
    "class/src/js/tour.js~Tour.html#instance-method-cancel",
    "src/js/tour.js~Tour#cancel",
    "method"
  ],
  [
    "src/js/tour.js~tour#complete",
    "class/src/js/tour.js~Tour.html#instance-method-complete",
    "src/js/tour.js~Tour#complete",
    "method"
  ],
  [
    "src/js/tour.js~tour#constructor",
    "class/src/js/tour.js~Tour.html#instance-constructor-constructor",
    "src/js/tour.js~Tour#constructor",
    "method"
  ],
  [
    "src/js/tour.js~tour#currentstep",
    "class/src/js/tour.js~Tour.html#instance-member-currentStep",
    "src/js/tour.js~Tour#currentStep",
    "member"
  ],
  [
    "src/js/tour.js~tour#done",
    "class/src/js/tour.js~Tour.html#instance-method-done",
    "src/js/tour.js~Tour#done",
    "method"
  ],
  [
    "src/js/tour.js~tour#getbyid",
    "class/src/js/tour.js~Tour.html#instance-method-getById",
    "src/js/tour.js~Tour#getById",
    "method"
  ],
  [
    "src/js/tour.js~tour#getcurrentstep",
    "class/src/js/tour.js~Tour.html#instance-method-getCurrentStep",
    "src/js/tour.js~Tour#getCurrentStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#hide",
    "class/src/js/tour.js~Tour.html#instance-method-hide",
    "src/js/tour.js~Tour#hide",
    "method"
  ],
  [
    "src/js/tour.js~tour#id",
    "class/src/js/tour.js~Tour.html#instance-member-id",
    "src/js/tour.js~Tour#id",
    "member"
  ],
  [
    "src/js/tour.js~tour#isactive",
    "class/src/js/tour.js~Tour.html#instance-method-isActive",
    "src/js/tour.js~Tour#isActive",
    "method"
  ],
  [
    "src/js/tour.js~tour#modal",
    "class/src/js/tour.js~Tour.html#instance-member-modal",
    "src/js/tour.js~Tour#modal",
    "member"
  ],
  [
    "src/js/tour.js~tour#next",
    "class/src/js/tour.js~Tour.html#instance-method-next",
    "src/js/tour.js~Tour#next",
    "method"
  ],
  [
    "src/js/tour.js~tour#options",
    "class/src/js/tour.js~Tour.html#instance-member-options",
    "src/js/tour.js~Tour#options",
    "member"
  ],
  [
    "src/js/tour.js~tour#removestep",
    "class/src/js/tour.js~Tour.html#instance-method-removeStep",
    "src/js/tour.js~Tour#removeStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#setupstep",
    "class/src/js/tour.js~Tour.html#instance-method-setupStep",
    "src/js/tour.js~Tour#setupStep",
    "method"
  ],
  [
    "src/js/tour.js~tour#show",
    "class/src/js/tour.js~Tour.html#instance-method-show",
    "src/js/tour.js~Tour#show",
    "method"
  ],
  [
    "src/js/tour.js~tour#start",
    "class/src/js/tour.js~Tour.html#instance-method-start",
    "src/js/tour.js~Tour#start",
    "method"
  ],
  [
    "src/js/tour.js~tour#steps",
    "class/src/js/tour.js~Tour.html#instance-member-steps",
    "src/js/tour.js~Tour#steps",
    "member"
  ],
  [
    "test/cypress/integration/a11y.spec.js",
    "test-file/test/cypress/integration/a11y.spec.js.html",
    "test/cypress/integration/a11y.spec.js",
    "testFile"
  ],
  [
    "test/cypress/integration/element-targeting.spec.js",
    "test-file/test/cypress/integration/element-targeting.spec.js.html",
    "test/cypress/integration/element-targeting.spec.js",
    "testFile"
  ],
  [
    "test/cypress/integration/modal.spec.js",
    "test-file/test/cypress/integration/modal.spec.js.html",
    "test/cypress/integration/modal.spec.js",
    "testFile"
  ],
  [
    "test/unit/evented.spec.js",
    "test-file/test/unit/evented.spec.js.html",
    "test/unit/evented.spec.js",
    "testFile"
  ],
  [
    "test/unit/modal.spec.js",
    "test-file/test/unit/modal.spec.js.html",
    "test/unit/modal.spec.js",
    "testFile"
  ],
  [
    "test/unit/step.spec.js",
    "test-file/test/unit/step.spec.js.html",
    "test/unit/step.spec.js",
    "testFile"
  ],
  [
    "test/unit/tour.spec.js",
    "test-file/test/unit/tour.spec.js.html",
    "test/unit/tour.spec.js",
    "testFile"
  ],
  [
    "test/unit/utils/cleanup.spec.js",
    "test-file/test/unit/utils/cleanup.spec.js.html",
    "test/unit/utils/cleanup.spec.js",
    "testFile"
  ],
  [
    "test/unit/utils/dom.spec.js",
    "test-file/test/unit/utils/dom.spec.js.html",
    "test/unit/utils/dom.spec.js",
    "testFile"
  ],
  [
    "test/unit/utils/general.spec.js",
    "test-file/test/unit/utils/general.spec.js.html",
    "test/unit/utils/general.spec.js",
    "testFile"
  ],
  [
    "test/unit/utils/modal.spec.js",
    "test-file/test/unit/utils/modal.spec.js.html",
    "test/unit/utils/modal.spec.js",
    "testFile"
  ]
]